#!/bin/sh
#
# Copyright (C) 2005-2010 Kazuyoshi Aizawa. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
#   notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#   notice, this list of conditions and the following disclaimer in the
#   documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
PATH=/usr/sbin:/bin

interface=`ifconfig -a |egrep "^[a-z]" | cut -f1 -d : | grep -v lo0`

case "$1" in
start)

        for i in $interface
        do
                ifconfig $i modinsert fwall@2

                if [ $? -eq 0 ]; then
                        echo "fwall module inserted to $i"
                fi
        done

	;;

stop)
        for i in $interface
        do
                while [ `ifconfig $i modlist |grep -c fwall` -ne 0 ];
                do
                        ifconfig $i modremove fwall@2
                done                
        done

	if [ $? -eq 0 ]; 
	then
		echo "fwall module removed from all interface"
	fi

        MODULEID=`modinfo | awk '/fwall/{ print $1 }'` 

        if [ $MODULEID ];then
        	modunload -i $MODULEID
        fi

        if [ $? -eq 0 ]; then
                echo "fwall module successfully unloaded"
        fi
	;;

*)
	echo "Usage: $0 { start | stop }"
	exit 1
	;;
esac
exit 0
